#!/usr/bin/env bash
# run.sh — master replication script for:
#   "Standard Methods Find Returns of 5-7%: A Comment on Clark and Nielsen (2026)"
#   Author: Lee Crawfurd
#
# Requirements:
#   - StataNow/Stata 16+ (STATA path below — edit if needed)
#   - Python 3.9+  with packages in requirements.txt
#   - R 4.x        with packages: dplyr, readr, jsonlite, meta, metasens, puniform,
#                  weightr, haven, robumeta (auto-installed to .r_libs/ on first run)
#
# Runtime: ~5–7 minutes (simulation step adds ~3 minutes)
#
# Usage:  ./run.sh
#
# Outputs:
#   output/figures/   — PDF/PNG figures (fig1–fig6)
#   output/           — stata_pub_bias_summary.{csv,log}, r_pub_bias_results.json,
#                       cn_simulation_results.json
#   overleaf/figures/ — synced copies for Overleaf compilation
#   output/tables/    — table1_egger, table2_petpeese, table5_summary (generated by 05_make_tables.py)
#   overleaf/tables/  — synced from output/tables/ by this script

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATA=/Applications/StataNow/StataMP.app/Contents/MacOS/stata-mp

mkdir -p "$HERE/output/figures"
mkdir -p "$HERE/output/tables"

echo "=== Step 1: Stata pub-bias methods (PET-PEESE, Egger, trim-and-fill, RE) ==="
# Also generates data/_r_copas_puniform_input.csv consumed by Step 2.
# NOTE: cd to project root before calling Stata so that c(pwd) is the root and
# Stata's own argument parser does not choke on spaces in the absolute path.
cd "$HERE"
"$STATA" -b do "code/01_pub_bias_stata.do"

echo "=== Step 2: R selection models (p-uniform*, Copas) ==="
R_LIBS="$HERE/.r_libs" Rscript "$HERE/code/02_selection_models_r.R" \
    "$HERE/data/_r_copas_puniform_input.csv" \
    "$HERE/output/r_pub_bias_results.json" \
    "$HERE/output/copas_metasens_plot.png"

echo "=== Step 3: Python figures ==="
python3 "$HERE/code/03_make_figures.py"

echo "=== Step 3b: CN simulation and alternative distribution fit ==="
python3 "$HERE/code/04_cn_simulation.py"

echo "=== Step 3c: Generate LaTeX tables from Stata CSV + R JSON ==="
python3 "$HERE/code/05_make_tables.py"

OVERLEAF="/Users/lee/Library/CloudStorage/Dropbox-CGDEducation/Lee Crawfurd/Apps/Overleaf/Returns meta-analysis"

echo "=== Step 4: Sync figures and tables to Overleaf ==="
cp "$HERE/output/figures/"*.pdf "$OVERLEAF/figures/"
cp "$HERE/output/figures/"*.png "$OVERLEAF/figures/" 2>/dev/null || true
cp "$HERE/output/copas_metasens_plot.png" "$OVERLEAF/figures/fig3_copas.png"
cp "$HERE/output/tables/"*.tex "$OVERLEAF/tables/"

echo "=== Done. ==="
echo "  Figures: output/figures/ and $OVERLEAF/figures/"
echo "  Tables:  output/tables/ and $OVERLEAF/tables/"
echo "  Stats:   output/stata_pub_bias_summary.csv"
